### ISSUE TITLE
Consider requiring CAS Login to prevent public exposure of student data

### ISSUE THREAD

**Issue by ErikBoesen** [kevinz917/holiday2020#12]
Currently I can access all students' info through your interface (or the JSON payload at https://holiday2020-service.herokuapp.com/card/allstudents) without any sort of authentication that I'm part of the Yale community - it may be worth requiring CAS login before you provide this information just in case Yale were to throw a fit about privacy.

**Comment by kevinz917** [comment]
Thank you! Launching new update tmr to fix this.

**Comment by kevinz917** [comment]
Fixed
